### ISSUE TITLE
Refactor the repository using mods 

### ISSUE THREAD

**Issue by FedericoPonzi** [FedericoPonzi/distributed-systems-bot#1]
When this project was developed, there was little or none consensus on how to structure a golang project. Still, there is no exact standard, but it would be nice to have a more conventional structure: https://github.com/golang-standards/project-layout based on mods.
Please let me know if you want to take a shot at it!

**Comment by shilangyu** [comment]
So move to go modules and organize in folders? I can do it, could you assign it to me?

**Comment by FedericoPonzi** [comment]
I've assigned it to you! Have fun!
